### PR TITLE
Fix command with extra parameters issue

### LINKED ISSUE #183: [PE-D] List command (residents) accepts additional arguments
For example, if a user keys in "list -group" accidentally with a space, it would still list residents. 
It seems to be the same case as other commands like edit as well i believe. 
Not sure if it's considered a bug but just letting yall know. Cheers.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: TheSpaceCuber/ped#1

### LINKED ISSUE #189: [PE-D] Dangerous command structure and parsing
When you are entering a command like clear-event, if you leave a space bar in between clear and - accidentally like I did, you will trigger the clear command and reset the entire address book instead. This is the same for any other command that is longer than a single word such as filter-event. Personally I feel that for new users, this is really dangerous as with one single typo, they can lose all their data. I would suggest adding more code to the parser to catch that the input has more text than normal commands.

(Before)

(After)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: bangyiwu/ped#1

### LINKED ISSUE #201: [PE-D] Clear command deletes everything
Its not clear in the UG that the clear command deletes both the residents list as well as the events list. The UG made it appear that it only clears the Residents column (as there was no separate command to clear only the residents list). It would be better if the UG was updated to reflect that as well as a separate command eg.clear-residents so users dont accidentally delete data unexpectedly

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: the-reefshark/ped#2

### PR DESCRIPTION
**Pull request by teekoksiang**
Update UG `clear` section by mentioning the command clears all events also.
Close #201. 

Restrict commands with no parameter throw `ParseException` when there is extra parameters.   
Close #183. 
Close #189.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddressBookParser.java [hunk 1]
```diff
@@ -63,18 +63,30 @@ public Command parseCommand(String userInput) throws ParseException {
...
 
         case ExitCommand.COMMAND_WORD:
+            if (!arguments.isEmpty()) {
+                throw new ParseException(MESSAGE_UNKNOWN_COMMAND);
+            }
             return new ExitCommand();
 
         case HelpCommand.COMMAND_WORD:
+            if (!arguments.isEmpty()) {
+                throw new ParseException(MESSAGE_UNKNOWN_COMMAND);
```
Comment (yanchenglee98) [inline src/main/java/seedu/address/logic/parser/AddressBookParser.java]: I think instead of throwing a generic `ParseException(MESSAGE_UNKNOWN_COMMAND)`, should throw `ParseException(HelpCommand.MESSAGE_USAGE)`.  The error can be more specific and help the user recover. Same applies for all the other commands

**Review by yanchenglee98 — COMMENTED** [review]
LGTM. Some minor changes only.

File: src/main/java/seedu/address/logic/parser/AddressBookParser.java (hunk 1 above)
Comment (teekoksiang) [reply src/main/java/seedu/address/logic/parser/AddressBookParser.java]: Good point! Updated the implementation.

**Review by yanchenglee98 — APPROVED** [review]
LGTM
